// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfA36wRU68zaiQQ_geeKvqwltGMekD58E',
    appId: '1:203297295583:web:2753f7a41cf60c772dad6a',
    messagingSenderId: '203297295583',
    projectId: 'fir-rifqi',
    authDomain: 'fir-rifqi.firebaseapp.com',
    storageBucket: 'fir-rifqi.appspot.com',
    measurementId: 'G-4JE799G8WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9msl1JbhE81_rDu1v6YcxhTyZHsrf11A',
    appId: '1:203297295583:android:3aa10fef3b8071192dad6a',
    messagingSenderId: '203297295583',
    projectId: 'fir-rifqi',
    storageBucket: 'fir-rifqi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44gXMu4SHS5nTzWf7LnKMgNSbckoWpes',
    appId: '1:203297295583:ios:0ede2875294ecade2dad6a',
    messagingSenderId: '203297295583',
    projectId: 'fir-rifqi',
    storageBucket: 'fir-rifqi.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44gXMu4SHS5nTzWf7LnKMgNSbckoWpes',
    appId: '1:203297295583:ios:0ede2875294ecade2dad6a',
    messagingSenderId: '203297295583',
    projectId: 'fir-rifqi',
    storageBucket: 'fir-rifqi.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfA36wRU68zaiQQ_geeKvqwltGMekD58E',
    appId: '1:203297295583:web:bb14308ae757e7672dad6a',
    messagingSenderId: '203297295583',
    projectId: 'fir-rifqi',
    authDomain: 'fir-rifqi.firebaseapp.com',
    storageBucket: 'fir-rifqi.appspot.com',
    measurementId: 'G-2HQRMLEH3B',
  );
}
